worker_processes auto;
pid /home/container/tmp/nginx.pid;
daemon off;

events {
    worker_connections 1024;
    multi_accept on;
}

error_log /home/container/logs/error.log warn;

http {
    include       /home/container/nginx/mime.types;
    default_type  application/octet-stream;

    sendfile        on;
    tcp_nopush      on;
    tcp_nodelay     on;
    keepalive_timeout 65;
    types_hash_max_size 2048;
    server_tokens   off;

    client_max_body_size 100m;

    proxy_temp_path       /home/container/tmp;
    client_body_temp_path /home/container/tmp;
    fastcgi_temp_path     /home/container/tmp;
    uwsgi_temp_path       /home/container/tmp;
    scgi_temp_path        /home/container/tmp;


    access_log /home/container/logs/access.log;
    access_log /dev/stdout;
    error_log  /home/container/logs/error.log warn;
    error_log  /dev/stdout warn;

    gzip on;
    gzip_disable "msie6";
    gzip_vary on;
    gzip_min_length 256;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;

    include /home/container/nginx/conf.d/*.conf;
}
